name: Close wontfix issues
on:
  issues:
    types: [opened, labeled]
jobs:
  close-wontfix:
    runs-on: ubuntu-latest
    steps:
      - name: Close issue if labeled wontfix
        if: contains(github.event.issue.labels.*.name, 'wontfix')
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}